enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 2

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Reddit]
enabled = false
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
build-mode = "both"
apkmirror-dpi = "120-640dpi"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
build-mode = "both"
apkmirror-dpi = "120-640dpi"
